import {parseHoldingsCSV,compareHoldings as compareAllocation} from '../savings/model.js';
import { lifecycle, futureValue, compareHoldings, portfolioHistory, STRATEGIES } from './model.js';
import { etfRequest, knownHistory, rememberHistory } from './api.js?v=20261005-recovery20';
import { shell,esc,fmt,pct,color,money,amount,tabs,selector,input,chart,donut } from './ui.js?v=20261005-stable18';
import { labelMobileTables } from './mobile.js?v=20261005-weeklist4';
const manualFunds=new Map();let allocation=50;
const tools=[['life','生命週期'],['single','單一標的'],['portfolio','投資組合'],['compare','相似度比較']];
const defaults={age:30,retire:60,lifespan:90,initial:100000,monthly:10000,annual:6,retirementAnnual:3};
const singleDefaults={initial:100000,monthly:10000,annual:6,dividendYield:5,depositRate:1.7};
let tab='life', lifeValues={...defaults}, singleValues={...singleDefaults}, symbol='0056', sub='dca', strategy='balanced', portfolioValues={initial:100000,monthly:10000,annual:6}, pair=['0050','006208'];
const metric=(label,value,small='')=>`<div><div class="metric-label">${label}</div><div class="metric-value">${value}</div>${small?`<small>${small}</small>`:''}</div>`;
export function mountSavings(host,{initialSelection}={}) {
  if(initialSelection?.symbol)symbol=initialSelection.symbol;
  if(initialSelection?.tab)tab=initialSelection.tab;
  if(initialSelection?.tab==='compare')pair[0]=symbol;
  const ui=shell(host,'存股計算'),{main,shadow,life}=ui;
  let mobilePane='settings';
  const phone=()=>matchMedia('(max-width:760px)').matches;
  function setPane(value){mobilePane=value;main.dataset.mobilePane=value;shadow.querySelectorAll('[data-pane]').forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.pane===value)));}
  function mobileNav(){return `<nav class="mobile-calculator-nav" aria-label="試算步驟"><button data-pane="settings" aria-pressed="${mobilePane==='settings'}">① 調整設定</button><button data-pane="result" aria-pressed="${mobilePane==='result'}">② 查看結果</button></nav>`;}
  let advanced=null,advancedSerial=0;let catalog=null, catalogError='', alive=true, generation=0, detail=null, comparison=null, compareError='', portfolioStat=null, status='', busy=false, error='', yieldMode='manual', formDirty=false;
  function header(){return `<header class="header"><div><div class="eyebrow">OX · INVESTMENT TOOLS</div><h2>存股計算</h2></div><small>規劃投入、配置與持股重疊</small></header><section class="card">${tabs(tools,tab)}</section>`;}
  function render(){if(!alive)return;advanced?.destroy();advanced=null;const serial=++advancedSerial;const draft=[...shadow.querySelectorAll('form input')].map(n=>({name:n.name,value:n.value}));const oldForm=shadow.querySelector('form')?.dataset.form;main.innerHTML=header()+(tab!=='compare'&&!(tab==='single'&&sub==='reinvest')?mobileNav():'')+(tab==='life'||catalog?({life:lifePage,single:singlePage,portfolio:portfolioPage,compare:comparePage}[tab])():catalogError?'<div class="empty">ETF 清單暫未取得，可先使用生命週期試算。</div>':'<div class="loading" role="status">正在取得 ETF 清單…</div>')+(catalogError?`<div class="notice" data-catalog-error role="status">${esc(catalogError)} <button data-retry>重新載入 ETF 清單</button></div>`:'')+`<p class="note">試算為固定報酬率情境，未扣除交易成本、稅負與通膨；歷史績效與配息不保證未來結果。</p>`;labelMobileTables(main);setPane(mobilePane);if(tab==='single'&&sub==='reinvest')import('../savings/view.js?v=20261005-weeklist4').then(module=>{const target=shadow.querySelector('[data-advanced]');if(alive&&serial===advancedSerial&&target)advanced=module.mountSavings(target,{calculatorOnly:true});});if(formDirty&&shadow.querySelector('form')?.dataset.form===oldForm)for(const d of draft){const n=shadow.querySelector(`input[name="${d.name}"]`);if(n)n.value=d.value;}}
  function lifePage(){let result;try{result=lifecycle(lifeValues);}catch(e){error=e.message;}
    return `<div class="layout"><section class="card card-pad"><h3 class="form-title">退休生活規劃</h3><form data-form="life"><div class="form-grid">${input('age','目前年齡',lifeValues.age,{min:18,max:109,suffix:'歲'})}${input('retire','退休年齡',lifeValues.retire,{min:18,max:109,suffix:'歲'})}${input('lifespan','預估壽命',lifeValues.lifespan,{min:19,max:110,suffix:'歲'})}${input('initial','初期投入',lifeValues.initial,{suffix:'元'})}${input('monthly','每月儲蓄',lifeValues.monthly,{suffix:'元'})}${input('annual','累積期年化報酬',lifeValues.annual,{min:-99,max:100,step:.1,suffix:'%'})}<div class="wide">${input('retirementAnnual','退休期年化報酬',lifeValues.retirementAnnual,{min:-99,max:100,step:.1,suffix:'%'})}</div></div><button class="primary submit">重新試算</button><p class="error" role="alert">${esc(error)}</p></form></section><section class="card card-pad"><div class="result-heading"><h3>你的退休資產曲線</h3><span class="pill">情境試算</span></div>${result?`<div class="metrics" style="margin-top:24px">${metric('退休後每月可用生活費',amount(result.withdrawal))}${metric(`${lifeValues.retire} 歲退休資產`,amount(result.wealth),`累計投入 ${amount(result.invested)}`)}</div>${chart(result.points,{label:'資產隨年齡變化',marker:lifeValues.retire})}<p class="note">每月底投入，退休後每月底提領；依設定於 ${lifeValues.lifespan} 歲用完資產。退休期使用 ${fmt(lifeValues.retirementAnnual,1)}% 年化報酬。</p>`:'<div class="empty">請修正左側設定後重新試算。</div>'}</section></div>`;
  }
  function singlePage(){
    if(sub==='reinvest')return `<section class="card" style="margin-top:16px">${tabs([['dca','定期定額'],['dividend','股息試算'],['reinvest','股息再投入']],sub,'data-single')}<div data-advanced></div></section>`;
    return `<div class="layout"><section class="card card-pad"><h3 class="form-title">選擇存股標的</h3>${selector(catalog.rows,symbol,'single-symbol','ETF')}<p class="status-line">${busy?'正在取得歷史配息與報酬…':esc(status)}</p>${tabs([['dca','定期定額'],['dividend','股息試算'],['reinvest','股息再投入']],sub,'data-single')}<form data-form="single" style="margin-top:18px"><div class="form-grid"><div class="wide">${input('initial',sub==='dca'?'初期投入金額':'一次投入金額',singleValues.initial,{suffix:'元'})}</div>${sub==='dca'?`${input('monthly','每月定期投入',singleValues.monthly,{suffix:'元'})}${input('annual','預期年化報酬率',singleValues.annual,{min:-99,max:100,step:.1,suffix:'%'})}`:`${input('dividendYield','預估年配息率',singleValues.dividendYield,{min:0,max:100,step:.01,suffix:'%'})}${input('depositRate','比較定存年利率',singleValues.depositRate,{min:0,max:30,step:.01,suffix:'%'})}`}</div>${sub==='dca'?`<button type="button" data-use-history class="submit" ${!Number.isFinite(detail?.annual)?'disabled':''}>帶入歷史年化 ${pct(detail?.annual)}</button><p class="note">期間 ${esc(detail?.historyStart||'—')}～${esc(detail?.date||'—')}。預設 6% 為可調整假設。</p>`:`<button type="button" data-use-yield class="submit" ${!Number.isFinite(detail?.threeYearYield)?'disabled':''}>帶入三年平均殖利率 ${pct(detail?.threeYearYield)}</button><p class="note">${detail?.threeYearYield!=null?'最近三個完整年度配息／各年年底股價的平均。':detail?.splitAffected?'歷史含分割，未確認配息基準前請自行設定。':'完整三年配息不足，請自行設定假設。'}定存利率由你自行設定。</p>`}<button class="primary submit">重新試算</button><p class="error" role="alert">${esc(error)}</p></form></section><section class="card card-pad">${sub==='dca'?dcaResult():dividendResult()}</section></div>`;
  }
  function dcaResult(){try{
    const points=Array.from({length:21},(_,x)=>({x,value:futureValue(singleValues.initial,singleValues.monthly,singleValues.annual,x)}));
    return `<div class="result-heading"><h3>定期累積，讓時間參與</h3><span class="pill">${esc(symbol)} · ${fmt(singleValues.annual,1)}% 情境</span></div><div class="metrics" style="margin-top:23px">${metric('10 年預估資產',amount(points[10].value))}${metric('20 年預估資產',amount(points[20].value))}</div>${chart(points,{unit:'年',label:'定期定額資產試算'})}<div class="scenario-grid">${[3,5,10,20].map(y=>`<div class="scenario"><small>${y} 年後</small><b>${money(points[y].value)}</b><small>投入 ${money(singleValues.initial+singleValues.monthly*y*12)}</small><div class="mini-bar"><span style="width:${Math.max(0,Math.min(100,points[y].value/Math.max(...points.map(p=>p.value))*100))}%"></span></div></div>`).join('')}</div>`;
  }catch(e){return `<div class="empty">${esc(e.message)}</div>`;}}
  function dividendResult(){const yearly=singleValues.initial*singleValues.dividendYield/100,bank=singleValues.initial*singleValues.depositRate/100;
    const source=yieldMode==='historical'?'三年平均殖利率':'自行設定配息率';
    return `<div class="result-heading"><h3>股息現金流</h3><span class="pill">${source}</span></div><div class="metrics" style="margin-top:23px">${metric('平均每月股息',amount(yearly/12))}${metric('預估一年股息',amount(yearly))}</div><table class="compact-table"><tr><td>ETF 配息頻率</td><td>${esc(catalog.rows.find(r=>r.symbol===symbol)?.frequency||detail?.frequency||'—')}</td></tr><tr><td>使用年配息率</td><td>${fmt(singleValues.dividendYield)}%</td></tr><tr><td>定存每月利息（平均）</td><td>${amount(bank/12)}</td></tr><tr><td>兩者每月差額</td><td class="${color(yearly-bank)}">${amount((yearly-bank)/12)}</td></tr></table><p class="note">月均金額為全年估計除以 12，實際入帳依 ETF 公告，非每月保證支付。配息可能包含收益平準金，亦可能減少本金。</p><h3 style="margin-top:24px">其他高股息標的</h3><div class="scenario-grid">${catalog.rows.filter(r=>r.tags.includes('dividend')&&r.symbol!==symbol&&!r.leveraged).sort((a,b)=>(b.aum||0)-(a.aum||0)).slice(0,4).map(r=>`<button class="scenario" data-symbol="${r.symbol}"><small>${r.symbol}</small><b style="font-size:13px">${esc(r.name)}</b><small>比較試算 →</small></button>`).join('')}</div>`;
  }
  function portfolioPage(){const s=STRATEGIES.find(x=>x.id===strategy), result=futureValue(portfolioValues.initial,portfolioValues.monthly,portfolioValues.annual,10);
    return `<div class="strategy-grid">${STRATEGIES.map(x=>`<button class="card strategy ${strategy===x.id?'active':''}" data-strategy="${x.id}"><b>${x.name}</b><small>${x.description}</small></button>`).join('')}</div><div class="layout"><section class="card card-pad"><h3>${s.name}</h3>${donut([{name:'股票',weight:s.stock},{name:'債券',weight:100-s.stock}].filter(r=>r.weight>0),'股債配置')}<table class="compact-table">${s.funds.map(([id,w])=>`<tr><td>${id} ${esc(catalog.rows.find(r=>r.symbol===id)?.name||'')}</td><td>${Math.round(w*100)}%</td></tr>`).join('')}</table><form data-form="portfolio" style="margin-top:20px"><div class="form-grid">${input('initial','初期投入',portfolioValues.initial,{suffix:'元'})}${input('monthly','每月投入',portfolioValues.monthly,{suffix:'元'})}<div class="wide">${input('annual','試算年化報酬率',portfolioValues.annual,{min:-99,max:100,step:.1,suffix:'%'})}</div></div><button type="button" data-portfolio-history class="submit" ${!portfolioStat?'disabled':''}>帶入組合歷史年化 ${pct(portfolioStat?.annual)}</button><button class="primary submit">重新試算</button><p class="error" role="alert">${esc(error)}</p></form></section><section class="card card-pad"><div class="result-heading"><h3>配置與資產展望</h3><span class="pill">${fmt(portfolioValues.annual,1)}% 情境</span></div><div class="metrics" style="margin-top:24px">${metric('預估 10 年後資產',amount(result))}${metric('累計投入',amount(portfolioValues.initial+portfolioValues.monthly*120))}</div>${chart(Array.from({length:11},(_,x)=>({x,value:futureValue(portfolioValues.initial,portfolioValues.monthly,portfolioValues.annual,x)})),{unit:'年',label:'組合情境試算'})}<div class="metrics" style="border:0;margin-top:20px">${metric('組合歷史年化報酬',pct(portfolioStat?.annual))}${metric('歷史年化波動度',portfolioStat?fmt(portfolioStat.volatility)+'%':'—')}</div><p class="status-line">${busy?'正在對齊各 ETF 的歷史日期…':esc(status)}</p><p class="note">${portfolioStat?`共同期間 ${portfolioStat.start}～${portfolioStat.end}；按月恢復上述配置，以調整後月收盤計算。`:'需各 ETF 至少 12 個共同完整月份；資料不足時不顯示歷史績效。'}策略為配置範例，可選擇後試算，未代你下單。</p></section></div>`;
  }
  function comparePage(){const a=comparison?.[0],b=comparison?.[1],r=compareHoldings(a,b);let combined=null;if(r){try{combined=compareAllocation(...[a,b].map(h=>({...h,holdings:h.holdings.map(x=>({...x,symbol:x.code}))})),allocation/100);}catch{}}const choices=[...new Map([...catalog.rows,...[...manualFunds.values()].map(h=>({symbol:h.symbol,name:h.name,currency:'TWD'}))].map(r=>[r.symbol,r])).values()];
    return `<section class="card card-pad" style="margin-top:16px"><form data-form="compare" class="compare-form">${selector(choices,pair[0],'a','第一檔 ETF')}<span class="vs">VS</span>${selector(choices,pair[1],'b','第二檔 ETF')}<button class="primary" ${busy?'disabled':''}>${busy?'比較中…':'比較持股'}</button><label class="allocation"><span data-allocation-label>第一檔配置 ${allocation}% ／ 第二檔 ${100-allocation}%</span><input name="allocation" type="range" min="0" max="100" value="${allocation}" aria-label="第一檔配置比例"></label></form><p class="status-line">${esc(status)}</p>${compareError?`<p class="notice" role="status">${esc(compareError)}</p>`:''}${r?`<div class="card compare-summary">${metric(r.sameDate?'持股相似度':'跨日參考重疊',fmt(r.overlap)+'%',r.complete?'完整揭露證券的權重交集':'已揭露持股之重疊下限')}${metric('重疊成分',r.rows.length+' 檔')}${metric('重疊程度',r.overlap>=70?'高':r.overlap>=30?'中':'低')}</div><p class="note">小叮嚀：${r.overlap>=70?'兩檔持股高度重疊，同時持有可能增加相同股票曝險。':'持股差異不等同低風險，仍需留意產業、區域與股債配置。'}${!r.sameDate?'兩檔揭露日期不同，此數值僅供跨日參考。':''}</p><div class="two-columns" style="margin-top:20px">${[a,b].map((h,i)=>`<article class="card card-pad"><h3>${pair[i]} ${esc(choices.find(x=>x.symbol===pair[i])?.name||'')}</h3><p class="note">持股日 ${esc(h.date)} · <a href="${esc(h.url)}" target="_blank" rel="noopener">${esc(h.source)}</a></p>${donut(h.sectors,pair[i])}<small>揭露證券占淨資產 ${fmt(h.coverage)}%</small></article>`).join('')}</div><section class="card overlap"><div class="bar"><h3>重疊成分股</h3><small>各自總權重 ${fmt(r.weightA)}% / ${fmt(r.weightB)}%</small></div><div class="table-scroll"><table class="etf-table"><thead><tr><th>股票名稱</th><th>${pair[0]} 權重</th><th>${pair[1]} 權重</th></tr></thead><tbody>${r.rows.map(h=>`<tr><td>${esc(h.code)} ${esc(h.name)}</td><td>${fmt(h.a)}%</td><td>${fmt(h.b)}%</td></tr>`).join('')||'<tr><td colspan="3">已揭露證券無重疊</td></tr>'}</tbody></table></div></section>${combined?`<details class="disclosure"><summary>合併配置全部持股（${combined.combined.length} 檔）</summary><div class="table-scroll"><table class="etf-table"><thead><tr><th>股票</th><th>第一檔權重</th><th>第二檔權重</th><th>合併配置</th></tr></thead><tbody>${combined.combined.map(h=>`<tr><td>${esc(h.symbol)} ${esc(h.name)}</td><td>${fmt(h.weightA)}%</td><td>${fmt(h.weightB)}%</td><td>${fmt(h.portfolioWeight)}%</td></tr>`).join('')}</tbody></table></div></details>`:''}<p class="note">相似度＝所有相同證券兩檔權重較小者加總；以基金淨資產為分母，保留現金及期貨差異，不把缺漏持股重算成 100%。產業依官方公司分類；無法對應的海外證券保留為「未分類」。</p>`:busy?'<div class="loading" role="status">正在取得兩檔 ETF 的持股明細…</div>':'<div class="empty">選擇兩檔 ETF，查看持股重疊與產業分布。</div>'}${manualForm()}</section>`;
  }
  function manualForm(){return `<details class="disclosure"><summary>匯入其他 ETF 持股</summary><p>使用發行商公布的持股清單，可將其他 ETF 加入比較。匯入資料僅保留在本次工具中。</p><form data-form="import"><div class="form-grid"><label>ETF 代號<input name="symbol" required pattern="00[0-9]{2,4}[A-Z]?" maxlength="8" placeholder="例如 00919"></label><label>ETF 名稱<input name="name" required maxlength="50"></label><label>資料日期<input type="date" name="date" required></label></div><label style="margin-top:12px">持股 CSV<textarea name="csv" rows="5" required placeholder="代號,名稱,權重%"></textarea></label><button class="submit">匯入並比較</button><p class="error">${esc(error)}</p></form></details>`;}
  async function loadSingle(){const id=++generation;busy=true;detail=null;status='';render();try{let h=knownHistory(symbol);if(!h){const r=await etfRequest('history',{symbol},life.signal);rememberHistory(r.rows);h=knownHistory(symbol);}if(id!==generation||!alive)return;detail=h;status=h?`歷史資料截至 ${h.date}`:'歷史資料尚未提供，可使用自訂假設試算。';if(Number.isFinite(h?.threeYearYield)){singleValues.dividendYield=Number(h.threeYearYield.toFixed(2));yieldMode='historical';}else yieldMode='manual';}catch(e){if(id!==generation||!alive)return;status=e.message;}busy=false;render();}
  async function loadPortfolio(){const id=++generation;busy=true;portfolioStat=null;status='';render();const s=STRATEGIES.find(x=>x.id===strategy);try{const missing=s.funds.map(([id])=>id).filter(id=>!knownHistory(id));if(missing.length){const data=await etfRequest('history',{symbols:missing.join(',')},life.signal);rememberHistory(data.rows);}if(id!==generation||!alive)return;portfolioStat=portfolioHistory(s.funds.map(([id])=>knownHistory(id)),s.funds.map(([,w])=>w));status=portfolioStat?'歷史資料已對齊':'部分 ETF 歷史資料不足，仍可自行設定報酬率試算。';}catch(e){if(id!==generation||!alive)return;status=e.message;}busy=false;render();}
  async function loadComparison(){const id=++generation;busy=true;comparison=null;compareError='';status='';render();try{const results=await Promise.allSettled(pair.map(symbol=>manualFunds.has(symbol)?Promise.resolve(manualFunds.get(symbol)):etfRequest('holdings',{symbol},life.signal)));if(id!==generation||!alive)return;comparison=results.map(r=>r.status==='fulfilled'?r.value:null);const unavailable=comparison.map((h,i)=>!h?.holdings?.length?pair[i]:null).filter(Boolean);if(unavailable.length)compareError=`${unavailable.join('、')} 暫時沒有可驗證的持股明細，無法計算相似度。可選擇元大、富邦、國泰或永豐 ETF，或在下方匯入其他發行人的持股。`;else status=`${pair[0]}：${comparison[0].date} · ${pair[1]}：${comparison[1].date}`;}catch(e){if(id!==generation||!alive)return;compareError=e.message;}busy=false;render();}
  function activate(){mobilePane='settings';generation++;formDirty=false;error='';busy=false;status='';if(!catalog&&tab!=='life'){render();return;}if(tab==='single')loadSingle();else if(tab==='portfolio')loadPortfolio();else if(tab==='compare')loadComparison();else render();}
  shadow.addEventListener('click',e=>{const b=e.target.closest('button');if(!b)return;
    if(b.dataset.pane){if(b.dataset.pane==='result'&&formDirty){shadow.querySelector('form[data-form]')?.requestSubmit();return;}setPane(b.dataset.pane);return;}
    if(b.dataset.tab){tab=b.dataset.tab;activate();}
    else if(b.dataset.single){mobilePane='settings';formDirty=false;sub=b.dataset.single;error='';render();}
    else if(b.dataset.strategy){formDirty=false;strategy=b.dataset.strategy;loadPortfolio();}
    else if(b.dataset.symbol){formDirty=false;symbol=b.dataset.symbol;loadSingle();}
    else if(b.hasAttribute('data-use-history')&&detail?.annual!=null){formDirty=false;singleValues.annual=Math.min(100,Number(detail.annual.toFixed(2)));render();}
    else if(b.hasAttribute('data-use-yield')&&detail?.threeYearYield!=null){formDirty=false;singleValues.dividendYield=Number(detail.threeYearYield.toFixed(2));yieldMode='historical';render();}
    else if(b.hasAttribute('data-portfolio-history')&&portfolioStat){formDirty=false;portfolioValues.annual=Math.min(100,Number(portfolioStat.annual.toFixed(2)));render();}
    else if(b.hasAttribute('data-retry'))load();
  },{signal:life.signal});
  shadow.addEventListener('input',e=>{if(e.target.matches('form[data-form] input'))formDirty=true;if(e.target.name==='allocation')shadow.querySelector('[data-allocation-label]').textContent='第一檔配置 '+e.target.value+'% ／ 第二檔 '+(100-Number(e.target.value))+'%';},{signal:life.signal});
  shadow.addEventListener('change',e=>{if(e.target.name==='single-symbol'){formDirty=false;symbol=e.target.value;loadSingle();}},{signal:life.signal});
  shadow.addEventListener('submit',e=>{const form=e.target.closest('form[data-form]');if(!form)return;e.preventDefault();formDirty=false;error='';const fd=new FormData(form);if(form.dataset.form==='compare'){pair=[fd.get('a'),fd.get('b')];allocation=Number(fd.get('allocation'));loadComparison();return;}
    if(form.dataset.form==='import'){try{const date=fd.get('date'),today=new Intl.DateTimeFormat('en-CA',{timeZone:'Asia/Taipei'}).format(new Date());if(!date||date>today)throw Error('請填寫有效的持股資料日期');const symbol=fd.get('symbol'),holdings=parseHoldingsCSV(fd.get('csv')).map(h=>({code:h.symbol,name:h.name,weight:h.weight})),coverage=holdings.reduce((s,h)=>s+h.weight,0);manualFunds.set(symbol,{symbol,name:fd.get('name'),date,holdings,sectors:[{name:'自行匯入，產業未分類',weight:coverage},{name:'未提供部位',weight:100-coverage}],coverage,complete:false,source:'自行匯入',url:'#'});pair[1]=symbol;loadComparison();}catch(e){error=e.message;render();shadow.querySelector('details.disclosure:last-child').open=true;}return;}
    const values=Object.fromEntries([...fd].map(([k,v])=>[k,Number(v)]));try{if(form.dataset.form==='life'){lifecycle(values);lifeValues=values;}else if(form.dataset.form==='single'){const next={...singleValues,...values};futureValue(next.initial,next.monthly,next.annual,20);if(next.dividendYield!==singleValues.dividendYield)yieldMode='manual';singleValues=next;}else{futureValue(values.initial,values.monthly,values.annual,10);portfolioValues=values;}}catch(err){error=err.message;}if(phone()&&!error)mobilePane='result';render();if(phone())shadow.querySelector('.mobile-calculator-nav')?.scrollIntoView({block:'start',behavior:'smooth'});
  },{signal:life.signal});
  async function load(){catalogError='';try{catalog=await etfRequest('catalog',{},life.signal);if(!alive)return;if(tab==='life')shadow.querySelector('[data-catalog-error]')?.remove();else activate();}catch(e){if(alive){catalogError=e.message;render();}}}
  activate();load();return {destroy(){alive=false;generation++;advancedSerial++;advanced?.destroy();ui.destroy();}};
}
