import { etfRequest, rememberHistory, knownHistory } from './api.js?v=20261005-recovery20';
import { matchesCategory } from './model.js';
import { shell, esc, fmt, money, signed, pct, color, tabs, sourceNote, iconSearch } from './ui.js?v=20261005-stable18';
import { fundCards, labelMobileTables } from './mobile.js?v=20261005-weeklist4';
const mainTabs=[['rank','排行榜'],['hot','熱門資訊'],['stock','股票型'],['bond','債券型']];
const groups={rank:[['volume','今日熱門'],['aum','資產規模'],['holders','持股人數'],['yield','殖利率'],['return1y','一年報酬']],hot:[['new','新上市'],['active','主動式'],['offering','新募集'],['radar','熱股雷達']],stock:[['all','全部'],['cap','市值'],['dividend','高股息'],['theme','主題']],bond:[['all','全部'],['treasury','長期公債'],['investment','投資級'],['emerging','新興市場'],['highyield','非投資級']]};
const columns=[['price','收盤價'],['changePct','漲跌幅'],['volume','成交量（股）'],['turnover','成交金額'],['yield','殖利率'],['return3m','3 個月報酬'],['return1y','1 年報酬'],['returnTotal','上市以來報酬'],['aum','規模（億元）'],['holders','持股人數'],['years','成立年數'],['expense','年度費用率'],['region','投資區域']];
let saved=new Set();try{saved=new Set(JSON.parse(localStorage.getItem('ox-tw-etf-watchlist')||'[]'));}catch{}
const state={main:'rank',sub:'volume',sort:'volume',direction:-1,q:'',page:0,onlySaved:false};
export function mountETF(host,{onSavings}={}) {
  const ui=shell(host,'ETF 精選'),{main,shadow,life}=ui;
  let catalog=null, loading=false, alive=true, enrichId=0, error='', offering=null, radar=null;
  const today=new Intl.DateTimeFormat('en-CA',{timeZone:'Asia/Taipei'}).format(new Date());
  function rows(){return (catalog?.rows||[]).map(r=>({...r,...knownHistory(r.symbol),date:r.date,url:r.url,source:r.source,performanceDate:knownHistory(r.symbol)?.date,frequency:r.frequency||knownHistory(r.symbol)?.frequency,years:r.inception?(new Date(today)-new Date(r.inception))/86400000/365.25:null})).filter(r=>matchesCategory(r,state.main,state.sub,today)&&(!state.onlySaved||saved.has(r.symbol))&&(`${r.symbol} ${r.name}`.toLowerCase().includes(state.q.toLowerCase()))).sort((a,b)=>{
    const x=a[state.sort],y=b[state.sort];if(x==null&&y==null)return a.symbol.localeCompare(b.symbol);if(x==null)return 1;if(y==null)return -1;
    return (typeof x==='string'?x.localeCompare(y):x-y)*state.direction;
  });}
  function cell(r,key){const v=r[key];
    if(['changePct','yield','return3m','return1y','returnTotal'].includes(key))return `<span class="${key==='yield'?'':color(v)}">${key==='yield'&&Number.isFinite(v)?fmt(v)+'%':pct(v)}</span>${key==='yield'?`<span class="cell-sub">${esc(r.frequency||'配息待取得')}</span>`:''}`;
    if(key==='years')return Number.isFinite(v)?fmt(v,1)+' 年':'—';
    if(key==='region')return esc(v);
    if(key==='turnover')return money(v);
    if(key==='expense')return Number.isFinite(v)?fmt(v)+'%'+`<span class="cell-sub">${esc(r.expenseYear)} 年</span>`:'—';
    return `<span class="${key==='price'?color(r.changePct):''}">${fmt(v,['volume','holders'].includes(key)?0:2)}</span>${key==='price'?`<span class="cell-sub">${esc(r.currency)} · ${esc(r.date||'日期待公布')}</span>`:''}`;
  }
  function table(){const filtered=rows();state.page=Math.min(state.page,Math.max(0,Math.ceil(filtered.length/20)-1));const displayed=filtered.slice(state.page*20,(state.page+1)*20);
    return `${fundCards(displayed,{saved,columns,cell,start:state.page*20})}<div class="mobile-sort"><label><span class="sort-label">排序</span><select name="mobile-sort" aria-label="ETF 排序">${columns.map(([key,label])=>`<option value="${key}" ${key===state.sort?'selected':''}>${label}</option>`).join('')}</select></label><button data-sort="${state.sort}" aria-label="切換排序方向">${state.direction===-1?'由高到低 ↓':'由低到高 ↑'}</button></div><div class="bar desktop-table-note"><span>${filtered.length} 檔 ETF <span class="wide-only">· 點選欄位可排序</span></span><small>左右滑動查看全部欄位 →</small></div><div class="table-scroll desktop-fund-scroll" tabindex="0" aria-label="ETF 數據表，可左右捲動"><table class="etf-table desktop-funds"><thead><tr><th>ETF 代號／名稱</th>${columns.map(([key,label])=>`<th aria-sort="${state.sort===key?(state.direction===-1?'descending':'ascending'):'none'}"><button data-sort="${key}">${label} ${state.sort===key?(state.direction===-1?'↓':'↑'):'↕'}</button></th>`).join('')}<th>工具</th></tr></thead><tbody>${displayed.map((r,i)=>`<tr><td><div class="identity"><span class="rank">${state.page*20+i+1}</span><button class="star ${saved.has(r.symbol)?'saved':''}" data-star="${r.symbol}" aria-label="${saved.has(r.symbol)?'移除':'加入'} ${r.symbol} 自選" aria-pressed="${saved.has(r.symbol)}">${saved.has(r.symbol)?'★':'☆'}</button><button class="link-btn" data-detail="${r.symbol}"><div class="symbol">${r.symbol}</div><div class="name">${esc(r.name)}</div></button></div></td>${columns.map(([key])=>`<td>${cell(r,key)}</td>`).join('')}<td><button data-calc="${r.symbol}">試算 ↗</button></td></tr>`).join('')||'<tr><td colspan="15">沒有符合條件的 ETF</td></tr>'}</tbody></table></div><div class="bar"><span>${filtered.length?state.page*20+1:0}–${Math.min((state.page+1)*20,filtered.length)} / ${filtered.length}</span><div class="pagination"><button data-page="-1" ${state.page===0?'disabled':''} aria-label="上一頁">‹</button><span>${state.page+1} / ${Math.max(1,Math.ceil(filtered.length/20))}</span><button data-page="1" ${(state.page+1)*20>=filtered.length?'disabled':''} aria-label="下一頁">›</button></div></div>`;
  }
  function render(){if(!alive)return;const focused=shadow.activeElement?.getAttribute('name'),cursor=shadow.activeElement?.selectionStart;const left=shadow.querySelector('.table-scroll')?.scrollLeft||0;const expanded=[...shadow.querySelectorAll('[data-fund-extra][open]')].map(n=>n.dataset.fundExtra);const dialogOpen=shadow.querySelector('dialog')?.open;if(dialogOpen)return;
    main.innerHTML=`<header class="header"><div><div class="eyebrow">OX · MARKET INDICATORS</div><h2>ETF 精選</h2></div><div class="toolbar"><label class="search">${iconSearch}<input type="search" name="search" value="${esc(state.q)}" placeholder="搜尋代號或名稱" aria-label="搜尋 ETF 代號或名稱"></label><button data-watch aria-label="只看自選 ETF" aria-pressed="${state.onlySaved}" class="${state.onlySaved?'primary':''}"><span aria-hidden="true">☆</span><span class="desktop-caption"> 自選</span></button><button data-refresh aria-label="${loading?'更新中':'更新 ETF 資料'}" ${loading?'disabled':''}><span class="desktop-caption">${loading?'更新中…':'更新資料'}</span><span class="mobile-refresh" aria-hidden="true">${loading?'…':'↻'}</span></button></div></header><section class="card">${tabs(mainTabs,state.main,'data-main')}<div class="filters">${groups[state.main].map(([id,name])=>`<button data-sub="${id}" class="${state.sub===id?'active':''}">${name}</button>`).join('')}</div><div data-content>${state.main==='hot'&&state.sub==='offering'?renderOfferings():state.main==='hot'&&state.sub==='radar'?renderRadar():table()}</div></section><div class="bar status-line">${sourceNote(catalog)}<span data-enrich-status></span></div>${error?`<div class="notice" role="status">${esc(error)}</div>`:''}<details class="disclosure"><summary>資料說明與計算方式</summary><p>股價為證交所與櫃買中心已公布收盤價，非即時行情。資產規模與人數依各來源最新公布，更新日期可能不同；外幣 ETF 的規模以該幣別計價。</p><p>報酬以 Yahoo Finance 調整後收盤價計算（含配息與分割調整）；不足完整期間顯示 —。殖利率＝最近一年已除息金額／該資料日收盤價，不代表未來配息；年度費用率來自投信公會最近完整年度公告（含經理、保管及交易等費用），各檔標示資料年份；未取得時不以經理費替代。<a href="https://www.twse.com.tw/zh/ETFortune/products" target="_blank" rel="noopener">證交所 ETF</a> · <a href="https://info.tpex.org.tw/ETF/zh/filter.html" target="_blank" rel="noopener">櫃買 ETF</a></p></details><dialog class="detail-dialog"><header><h3 data-dialog-title></h3><button data-close aria-label="關閉 ETF 詳情">✕</button></header><div data-dialog-body></div></dialog>`;
    main.dataset.etfCategory=state.main;labelMobileTables(main);for(const n of shadow.querySelectorAll('[data-fund-extra]'))n.open=expanded.includes(n.dataset.fundExtra);
    const scroll=shadow.querySelector('.table-scroll');if(scroll)scroll.scrollLeft=left;
    if(focused){const node=shadow.querySelector(`[name="${focused}"]`);node?.focus({preventScroll:true});if(cursor!==null&&node?.type==='search')node.setSelectionRange(cursor,cursor);}
  }
  function renderOfferings(){if(!offering)return '<div class="loading" role="status">正在取得募集公告…</div>';return `<div class="bar"><span>募集／申報生效公告</span><small>公告日與募集起日分開顯示</small></div>${offering.rows?.map(r=>`<article class="offer"><b>${esc(r.name||r.title)}</b><p>${esc(r.title)}</p><small>${esc(r.date)} · ${esc(r.status||'依公告')} · 募集開始 ${esc(r.startDate||'—')}</small> <a href="${esc(r.url)}" target="_blank" rel="noopener">查看原文 ↗</a></article>`).join('')||'<div class="empty">目前來源未提供可確認的募集公告。</div>'}`;}
  function renderRadar(){if(!radar)return '<div class="loading" role="status">正在整理 ETF 持股熱度…</div>';return `<div class="bar"><span>已接入 ${radar.covered||0} 檔 ETF 的持股</span><small>持有檔數為資料覆蓋範圍內統計</small></div><div class="table-scroll"><table class="etf-table"><thead><tr><th>股票</th><th>近 5 日漲幅</th><th>ETF 持有數</th><th>交易警示</th><th>成交量（股）</th><th>成交金額</th></tr></thead><tbody>${(radar.rows||[]).map(r=>`<tr><td><b>${esc(r.symbol)} ${esc(r.name)}</b></td><td class="${color(r.change5d)}">${pct(r.change5d)}</td><td>${r.count}</td><td>${esc(r.warning||'—')}</td><td>${fmt(r.volume,0)}</td><td>${money(r.turnover)}</td></tr>`).join('')}</tbody></table></div>${radar.error?`<div class="notice">${esc(radar.error)}</div>`:''}`;}
  async function enrich(force=false){const token=++enrichId;if(state.main==='hot'&&['offering','radar'].includes(state.sub)){
    try{const result=await etfRequest(state.sub,force?{refresh:'1'}:{},life.signal);if(token!==enrichId)return;if(state.sub==='offering')offering=result;else radar=result;render();}catch(e){if(!alive)return;error=e.message;offering??={rows:[]};radar??={rows:[],error:e.message};render();}return;
  }
    const candidates=(['yield','return1y'].includes(state.sub)&&state.main==='rank'?rows():rows().slice(state.page*20,(state.page+1)*20)).filter(r=>force||!knownHistory(r.symbol));
    for(let i=0;i<candidates.length;i+=8){if(!alive||token!==enrichId)return;const status=shadow.querySelector('[data-enrich-status]');if(status)status.textContent=`補齊配息與報酬 ${i}/${candidates.length}`;
      try{const data=await etfRequest('history',{symbols:candidates.slice(i,i+8).map(r=>r.symbol).join(','),...(force?{refresh:'1'}:{})},life.signal);rememberHistory(data.rows);if(!alive||token!==enrichId)return;render();}catch(e){if(!alive)return;error='部分歷史資料暫時無法取得，已保留收盤資料。';render();break;}
    }
  }
  async function load(refresh=false){if(loading)return;loading=true;render();try{catalog=await etfRequest('catalog',refresh?{refresh:'1'}:{},life.signal);if(!alive)return;error=catalog.stale?catalog.status:'';}catch(e){if(!alive)return;error=e.message;}loading=false;if(!catalog){main.innerHTML=`<div class="empty">${esc(error)}<button data-refresh>重新載入</button></div>`;return;}render();await enrich(refresh);}
  async function detail(symbol){const row=catalog.rows.find(r=>r.symbol===symbol);const dialog=shadow.querySelector('dialog');shadow.querySelector('[data-dialog-title]').textContent=symbol+' '+row.name;const body=shadow.querySelector('[data-dialog-body]');body.innerHTML='<div class="loading">載入 ETF 詳情…</div>';dialog.showModal();
    try{let h=knownHistory(symbol);if(!h){const data=await etfRequest('history',{symbol},life.signal);rememberHistory(data.rows);h=knownHistory(symbol)||{};}if(!dialog.isConnected)return;
      body.innerHTML=`<div class="metrics"><div><div class="metric-label">官方收盤 ${esc(row.date)}</div><div class="metric-value ${color(row.changePct)}">${fmt(row.price)}</div><small>${pct(row.changePct)} · ${row.currency}</small></div><div><div class="metric-label">近一年配息殖利率</div><div class="metric-value">${Number.isFinite(h.yield)?fmt(h.yield)+'%':'—'}</div><small>${esc(row.frequency||h.frequency||'—')}</small></div></div><table class="compact-table"><tr><td>基金成立</td><td>${esc(row.inception||'—')}</td></tr><tr><td>發行公司</td><td>${esc(row.issuer)}</td></tr><tr><td>追蹤指數</td><td>${esc(row.index||'主動管理／未揭露')}</td></tr><tr><td>3 個月／1 年報酬</td><td>${pct(h.return3m)} / ${pct(h.return1y)}</td></tr><tr><td>可用歷史期間</td><td>${esc(h.historyStart||'—')}～${esc(h.date||'—')}</td></tr></table><p class="note">${esc(row.source)} · <a href="${esc(row.url)}" target="_blank" rel="noopener">官方資料 ↗</a> ${h.url?`· <a href="${esc(h.url)}" target="_blank" rel="noopener">報酬來源 ↗</a>`:''}</p><div class="actions"><button class="primary" data-calc="${symbol}">存股試算</button><button data-compare="${symbol}">相似度比較</button></div>`;
    }catch(e){body.innerHTML=`<div class="empty">${esc(e.message)}</div>`;}
  }
  shadow.addEventListener('input',e=>{if(e.target.name==='search'){state.q=e.target.value;state.page=0;render();}},{signal:life.signal});
  shadow.addEventListener('change',e=>{if(e.target.name==='search')enrich();if(e.target.name==='mobile-sort'){state.sort=e.target.value;if(state.main==='rank')state.sub=groups.rank.some(([id])=>id===state.sort)?state.sort:'volume';state.direction=-1;state.page=0;render();enrich();}},{signal:life.signal});
  shadow.addEventListener('click',e=>{const b=e.target.closest('button');if(!b)return;
    if(b.hasAttribute('data-main')){state.main=b.dataset.main;state.sub=groups[state.main][0][0];state.page=0;state.sort=state.main==='hot'?'listingDate':'volume';state.direction=-1;render();enrich();}
    else if(b.hasAttribute('data-sub')){state.sub=b.dataset.sub;state.page=0;if(state.main==='rank'){state.sort=state.sub;state.direction=-1;}render();enrich();}
    else if(b.dataset.sort){state.direction=state.sort===b.dataset.sort?-state.direction:-1;state.sort=b.dataset.sort;state.page=0;render();enrich();}
    else if(b.dataset.page){state.page+=Number(b.dataset.page);render();enrich();}
    else if(b.dataset.star){saved.has(b.dataset.star)?saved.delete(b.dataset.star):saved.add(b.dataset.star);try{localStorage.setItem('ox-tw-etf-watchlist',JSON.stringify([...saved]));}catch{}render();}
    else if(b.hasAttribute('data-watch')){state.onlySaved=!state.onlySaved;state.page=0;render();enrich();}
    else if(b.hasAttribute('data-refresh'))load(true);
    else if(b.dataset.detail)detail(b.dataset.detail);
    else if(b.hasAttribute('data-close'))shadow.querySelector('dialog')?.close();
    else if(b.dataset.calc||b.dataset.compare){shadow.querySelector('dialog')?.close();onSavings?.({symbol:b.dataset.calc||b.dataset.compare,tab:b.dataset.compare?'compare':'single'});}
  },{signal:life.signal});
  load();return {destroy(){alive=false;enrichId++;ui.destroy();}};
}
