import {projectSavings,compareHoldings,parseHoldingsCSV} from './model.js';
import {escape as e,number} from '../research-ui.js';
let state={tab:'calculator',initial:100000,monthly:10000,years:10,priceGrowth:0,dividendYield:0,reinvest:true,a:'0050',b:'0056',allocation:50};
export function mountSavings(host,{calculatorOnly=false}={}){
 const life=new AbortController(),root=document.createElement('section');root.className='tws tws-savings';host.append(root);let funds=[];
 root.innerHTML=`<link rel="stylesheet" href="${new URL('../screener/style.css?v=20261002-compact1',import.meta.url)}"><link rel="stylesheet" href="${new URL('./style.css?v=20261002-compact1',import.meta.url)}"><div class="tws-title"><div><h2>存股計算</h2><p>規劃投入，檢查 ETF 配置是否重複</p></div></div><div class="tws-main-tabs"><button data-tab="calculator" aria-pressed="true">存股試算</button><button data-tab="overlap" aria-pressed="false">ETF 重疊比較</button></div><div data-calculator><div class="tws-savings-layout"><form data-calc-form class="tws-savings-form"><h3>投入與報酬假設</h3>${[['initial','起始本金','元',0,1e10,1],['monthly','每月投入','元',0,1e8,1],['years','投資期間','年',1,60,1],['priceGrowth','年股價成長率','%',-99,100,.1],['dividendYield','年現金殖利率','%',0,30,.1]].map(([key,label,unit,min,max,step])=>`<label>${label}<span><input name="${key}" type="number" inputmode="decimal" min="${min}" max="${max}" step="${step}" value="${state[key]}" required><small>${unit}</small></span></label>`).join('')}<label class="tws-reinvest"><input type="checkbox" name="reinvest" ${state.reinvest?'checked':''}>股息再投入</label><button class="tws-primary" type="submit">計算</button><p class="tws-muted">報酬與殖利率均由你自行假設。股價成長率不含股息，避免重複計算。</p></form><div data-projection></div></div><details class="tws-help"><summary>試算方式與限制</summary><p>每月底投入固定金額；股價成長率轉為月複利。配息簡化為每月按資產 × 年殖利率 ÷ 12 計算，可選再投入。未再投入的股息列為現金，不計利息。</p><p>未納入手續費、稅負、通膨與除權息調整。這是固定假設下的數學試算，不是歷史回測或未來獲利預測；ETF配息可能含收益平準金。</p></details></div><div data-overlap hidden><div class="tws-etf-select"><label>ETF A<select data-fund="a" aria-label="ETF A"><option>載入中…</option></select></label><span>×</span><label>ETF B<select data-fund="b" aria-label="ETF B"><option>載入中…</option></select></label></div><label class="tws-allocation">配置比例 <b data-allocation-label>A 50% ／ B 50%</b><input type="range" min="0" max="100" value="${state.allocation}" data-allocation aria-label="ETF A 配置比例"></label><div data-comparison role="status">正在載入發行商持股資料…</div><details class="tws-help"><summary>重疊率怎麼算？</summary><p><b>基金權重重疊率</b>＝共同股票各自權重較小值的總和。保留原基金權重，未把現金、期貨、債券當成股票。<b>股票部位相似度</b>先將各基金的股票權重各自正規化為100%，再加總共同權重較小值。</p><p>合併配置權重＝A權重 × A配置比例 ＋ B權重 × B配置比例。不同資料日期會特別標示；本表只比較直接股票持股，未穿透其他ETF、不含衍生品曝險。重疊率不代表預期報酬或風險高低。</p></details><details class="tws-help"><summary>匯入其他 ETF 持股</summary><form data-import><p>貼上發行商完整股票清單。格式：代號,名稱,權重%（每行一檔）；只匯入前幾大持股時，結果僅代表已提供清單。</p><div class="tws-import-fields"><label>ETF 名稱<input name="name" maxlength="40" required placeholder="例如：00878 國泰永續高股息"></label><label>資料日期<input name="date" type="date" required></label></div><textarea name="csv" rows="6" required aria-label="持股CSV" placeholder="代號,名稱,權重%"></textarea><button type="submit">加入比較</button><p data-import-status role="status"></p></form></details></div>`;
 const q=s=>root.querySelector(s);
 function tab(id){state.tab=id;q('[data-calculator]').hidden=id!=='calculator';q('[data-overlap]').hidden=id!=='overlap';root.querySelectorAll('[data-tab]').forEach(el=>el.setAttribute('aria-pressed',String(el.dataset.tab===id)));}
 function calculate(){try{const form=q('[data-calc-form]');if(!form.reportValidity())return;for(const k of ['initial','monthly','years','priceGrowth','dividendYield'])state[k]=Number(form.elements[k].value);state.reinvest=form.elements.reinvest.checked;const result=projectSavings(state);const max=Math.max(...result.series.map(p=>Math.max(p.total,p.principal)),1),pt=(p,key)=>`${40+p.year/state.years*600},${210-p[key]/max*185}`,path=k=>result.series.map((p,i)=>(i?'L':'M')+pt(p,k)).join(' ');
 q('[data-projection]').innerHTML=`<div class="tws-projection-title"><span>${state.years} 年後・假設試算</span><h3>${number(result.total,0)} <small>元</small></h3><p>資產 ${number(result.assets,0)} ＋ 未再投入現金 ${number(result.cash,0)}</p></div><div class="tws-metrics">${[['累計本金',number(result.principal,0)+' 元'],['累計股息',number(result.dividends,0)+' 元'],['期末每月股息試算',number(result.monthlyIncome,0)+' 元']].map(([k,v])=>`<div><small>${k}</small><strong>${v}</strong></div>`).join('')}</div><div class="tws-chart"><div><span>● 總資產（含現金）</span><small>┄ 投入本金</small></div><svg viewBox="0 0 680 242" role="img" aria-label="${state.years}年存股試算，期末總資產${number(result.total,0)}元，投入本金${number(result.principal,0)}元"><path d="M40 25V210H640" fill="none" stroke="#ffffff28"/><path d="${path('principal')}" fill="none" stroke="#888" stroke-width="2" stroke-dasharray="5 5"/><path d="${path('total')}" fill="none" stroke="#eee" stroke-width="2.5"/><text x="40" y="234" fill="#999" font-size="11">現在</text><text x="615" y="234" fill="#999" font-size="11">${state.years}年</text></svg></div><details class="tws-yearly"><summary>逐年明細</summary><div class="tws-results-scroll"><table><thead><tr><th>年份</th><th>投入本金</th><th>總資產</th><th>累計股息</th></tr></thead><tbody>${result.series.map(p=>`<tr><td>${p.year}</td><td>${number(p.principal,0)}</td><td>${number(p.total,0)}</td><td>${number(p.dividends,0)}</td></tr>`).join('')}</tbody></table></div></details>`;
 for(const table of root.querySelectorAll('table')){const labels=[...table.querySelectorAll('th')].map(x=>x.textContent);for(const row of table.querySelectorAll('tbody tr'))[...row.cells].forEach((cell,i)=>cell.dataset.label=labels[i]||'');}
 }catch(error){q('[data-projection]').textContent=error.message;}}
 function compare(){const a=funds.find(f=>f.symbol===state.a),b=funds.find(f=>f.symbol===state.b);if(!a||!b){q('[data-comparison]').textContent='尚無可比較的持股資料，可匯入其他 ETF 清單。';return;}if(a.symbol===b.symbol){q('[data-comparison]').innerHTML='<div class="tws-notice">請選擇兩檔不同的 ETF。</div>';return;}try{const result=compareHoldings(a,b,state.allocation/100);q('[data-allocation-label]').textContent=`A ${state.allocation}% ／ B ${100-state.allocation}%`;
 q('[data-comparison]').innerHTML=`<div class="tws-etf-dates"><div><b>${e(a.name)}</b><span>${e(a.date)} · ${a.holdings.length} 檔 · 股票權重 ${number(result.totalA)}%</span>${a.sourceUrl?`<a href="${e(a.sourceUrl)}" target="_blank" rel="noopener">${e(a.source)} ↗</a>`:'<small>使用者匯入清單</small>'}</div><div><b>${e(b.name)}</b><span>${e(b.date)} · ${b.holdings.length} 檔 · 股票權重 ${number(result.totalB)}%</span>${b.sourceUrl?`<a href="${e(b.sourceUrl)}" target="_blank" rel="noopener">${e(b.source)} ↗</a>`:'<small>使用者匯入清單</small>'}</div></div>${!result.sameDate?'<div class="tws-notice">兩檔資料日期不同，重疊率依各自最近已取得的持股計算。</div>':''}${a.manual||b.manual?'<div class="tws-notice">含自行匯入資料；若清單不完整，結果僅涵蓋已提供股票。</div>':''}${a.stale||b.stale?'<div class="tws-notice">來源更新暫時失敗，保留上次已驗證持股。</div>':''}<div class="tws-overlap-score"><div><small>基金權重重疊率</small><strong>${number(result.overlap)}<em>%</em></strong><div class="tws-overlap-track"><i style="width:${Math.min(result.overlap,100)}%"></i></div></div><div><small>共同持股</small><strong>${result.shared.length}<em>檔</em></strong><p>股票部位相似度 ${number(result.equityOverlap)}%</p></div></div><h3>共同持股 <small>${result.shared.length}</small></h3><div class="tws-results-scroll"><table><thead><tr><th>股票</th><th>A 權重</th><th>B 權重</th><th>重疊權重</th><th>合併配置</th></tr></thead><tbody>${result.shared.map(s=>`<tr><td><b>${e(s.name)}</b><small>${e(s.symbol)}</small></td><td>${number(s.weightA)}%</td><td>${number(s.weightB)}%</td><td>${number(s.common)}%</td><td>${number(s.portfolioWeight)}%</td></tr>`).join('')}</tbody></table>${!result.shared.length?'<p class="tws-empty">已提供的股票清單沒有共同持股。</p>':''}</div><details class="tws-yearly"><summary>合併配置全部持股（${result.combined.length} 檔）</summary><div class="tws-results-scroll"><table><thead><tr><th>股票</th><th>A 權重</th><th>B 權重</th><th>合併配置</th></tr></thead><tbody>${result.combined.map(s=>`<tr><td>${e(s.name)} ${e(s.symbol)}</td><td>${number(s.weightA)}%</td><td>${number(s.weightB)}%</td><td>${number(s.portfolioWeight)}%</td></tr>`).join('')}</tbody></table></div></details>`;
 }catch(error){q('[data-comparison]').textContent=error.message;}}
 function options(){for(const key of ['a','b']){const el=q(`[data-fund="${key}"]`);el.innerHTML=funds.map(f=>`<option value="${e(f.symbol)}">${e(f.symbol)} ${e(f.name)}</option>`).join('');if(!funds.some(f=>f.symbol===state[key]))state[key]=funds[key==='a'?0:1]?.symbol||funds[0]?.symbol;el.value=state[key]||'';}compare();}
 root.addEventListener('click',ev=>{const b=ev.target.closest('[data-tab]');if(b)tab(b.dataset.tab);},{signal:life.signal});
 q('[data-calc-form]').addEventListener('submit',ev=>{ev.preventDefault();calculate();if(matchMedia('(max-width:760px)').matches)q('[data-projection]').scrollIntoView({block:'start',behavior:'smooth'});},{signal:life.signal});
 root.addEventListener('change',ev=>{if(ev.target.dataset.fund){state[ev.target.dataset.fund]=ev.target.value;compare();}},{signal:life.signal});
 q('[data-allocation]').addEventListener('input',ev=>{state.allocation=Number(ev.target.value);compare();},{signal:life.signal});
 q('[data-import]').addEventListener('submit',ev=>{ev.preventDefault();try{const f=ev.target,holdings=parseHoldingsCSV(f.elements.csv.value),date=f.elements.date.value;if(date>new Date().toLocaleDateString('en-CA',{timeZone:'Asia/Taipei'}))throw Error('資料日期不能在未來');const symbol='自訂-'+(funds.filter(f=>f.manual).length+1);funds.push({symbol,name:f.elements.name.value.trim(),date,holdings,manual:true});state.b=symbol;options();q('[data-import-status]').textContent='已加入 '+holdings.length+' 檔持股，此清單只保留於本次工具畫面。';}catch(error){q('[data-import-status]').textContent=error.message;}},{signal:life.signal});
 tab(calculatorOnly?'calculator':state.tab);calculate();if(calculatorOnly){q('.tws-main-tabs').hidden=true;q('.tws-title').hidden=true;return {destroy(){life.abort();root.remove();}};}fetch(new URL('../../../../data/tw-etf-holdings.json',import.meta.url),{signal:life.signal,cache:'no-cache'}).then(r=>{if(!r.ok)throw Error();return r.json();}).then(data=>{funds=data.funds||[];options();}).catch(error=>{if(error.name!=='AbortError'){q('[data-comparison]').textContent='發行商持股暫時無法載入，可匯入官方清單比較。';root.querySelectorAll('[data-fund]').forEach(el=>el.innerHTML='<option>尚無資料</option>');}});
 return {destroy(){life.abort();root.remove();}};
}
