import {normalizeTWStockCard,escapeTW} from './radar-card.js';
import {number,pct,money,direction} from './research-ui.js';
export function riskDetailContent(source,research){
 const row=normalizeTWStockCard(source);if(!row)return '';
 const d=row.disposition,date=row.dataDate||d.asOf;
 const flow=research?.date===date?research?.stocks?.find(s=>s.symbol===row.symbol&&s.market===row.market):null;
 const status=d.riskLabel||(d.repeatRiskDays!==null?`最快 ${d.repeatRiskDays} 個交易日後可能再次處置`:d.riskDays!==null?`最快 ${d.riskDays} 個交易日後可能進入處置`:d.noRepeatRisk===true?'近期無再次處置風險':d.status==='active'||d.status==='release'?'官方未提供再次處置預警':'尚無處置預警資料');
 const period=d.startDate&&d.endDate?`${d.startDate} ～ ${d.endDate}`:'';
 const release=(d.status==='release'||d.status==='active')?(d.releaseDays===0?'今日仍處置，收盤後期間結束':d.releaseDays!==null?`${d.releaseDays} 個交易日後出關`:'出關日期待更新'):'';
 const metric=(label,value,kind='')=>`<div class="tw-risk-metric"><small>${escapeTW(label)}</small><strong class="${kind}">${escapeTW(value)}</strong></div>`;
 const values=[['成交量（張）',number(Number.isFinite(row.volume)?row.volume/1000:null,0)],['成交值',money(row.turnoverTwd)],['週轉率',pct(row.turnoverRate)],['券資比',pct(row.shortMarginRatio)],['當沖率',pct(row.dayTradeRate)],['當沖損益',money(row.dayTradeProfit)],['當沖獲利率',pct(row.dayTradeProfitRate)],['當沖成交量（張）',number(Number.isFinite(row.dayTradeVolume)?row.dayTradeVolume/1000:null,0)],['三大法人淨買賣（估算）',money(flow?.netTwd),direction(flow?.netTwd)],['外資金額（估算）',money(flow?.foreignTwd),direction(flow?.foreignTwd)],['投信金額（估算）',money(flow?.trustTwd),direction(flow?.trustTwd)],['自營商金額（估算）',money(flow?.dealerTwd),direction(flow?.dealerTwd)]].filter(([,value])=>value!=='—');
 const facts=[['處置公告日',d.announcementDate],['處置開始',d.startDate],['處置迄日（含當日）',d.endDate],['預計恢復一般交易',d.resumeDate],['處置措施',d.measures],['公告次數',d.announcementCount],['剩餘交易日',d.releaseDays],['撮合間隔',d.batchMinutes!==null?`${d.batchMinutes} 分鐘`:null],['資料日期',d.asOf||date]].filter(([,value])=>value!==null&&value!==undefined&&value!=='');
 const fullNotices=[['處置措施公告',d.announcementDate,d.detail],['注意交易資訊公告',d.noticeTextDate||d.noticeDate,d.noticeText],['累計預警依據',d.noticeDate,d.riskBasis]].filter(([, ,text])=>text);
 const announcements=fullNotices.map(([title,date,text])=>`<details class="tw-risk-announcement" open><summary><b>${escapeTW(title)}</b><small>${escapeTW(date)}</small></summary><p class="tw-risk-announcement-text">${escapeTW(text)}</p></details>`).join('');
 const links=row.market==='TPEX'?['https://www.tpex.org.tw/zh-tw/announce/market/disposal.html','https://www.tpex.org.tw/zh-tw/announce/market/attention.html']:['https://www.twse.com.tw/zh/announcement/punish.html','https://www.twse.com.tw/zh/announcement/notice.html'];
 return `<div class="tw-stock-detail-head"><div><small>OX TW · 風險與處置分析</small><h3>${escapeTW(row.name)} <span>${escapeTW(row.symbol)}</span></h3></div><button type="button" data-twr-close aria-label="返回雷達">×</button></div><div class="tw-risk-quote-grid"><section class="tw-risk-quote ${direction(row.changePct)}"><strong>${number(row.price)}</strong><b>${number(row.change)} (${pct(row.changePct)})</b></section><section class="tw-risk-analysis"><small>風險天數分析</small><strong class="${status.includes('最快')?'urgent':''}">${escapeTW(status)}</strong>${d.riskBasis&&d.detail?`<p>${escapeTW(d.riskBasis)}</p>`:''}${d.riskProgress!==null?`<div class="tw-risk-progress"><i style="width:${d.riskProgress}%"></i></div>`:''}</section></div>${facts.length?`<div class="tw-risk-metrics">${facts.map(([label,value])=>metric(label,value)).join('')}</div>`:''}${d.condition?`<p>${escapeTW(d.condition)}</p>`:''}${values.length?`<div class="tw-risk-metrics">${values.map(([label,value,kind])=>metric(label,value,kind)).join('')}</div>`:''}<div class="tw-risk-tags"><span>${row.market==='TPEX'?'上櫃':'上市'}</span>${row.industry?`<span>${escapeTW(row.industry)}</span>`:''}${d.batchMinutes?`<span>${d.batchMinutes}分盤</span>`:''}${[['資',d.margin],['券',d.short],['沖',d.dayTrade],['期',d.futures]].filter(([,value])=>value!==null).map(([name,value])=>`<span>${name} ${value?'✓':'×'}</span>`).join('')}</div><nav class="tw-risk-links">${links.map((url,i)=>`<a href="${url}" target="_blank" rel="noopener noreferrer">${i?'注意歷史':'處置歷史'} ↗</a>`).join('')}<a href="https://mops.twse.com.tw/" target="_blank" rel="noopener noreferrer">自結紀錄（公開資訊）↗</a></nav>${period||release?`<p>${escapeTW(release||'處置期間 '+period)}</p>`:''}<footer><small>預警須後續達官方注意標準才可能處置。</small><button type="button" data-twr-chart>跳到圖表</button></footer>${announcements}`;
}
