import { guardStyledContent } from '../../../components/style-ready.js?v=20261005-stable18';
import { GROUPS, FIELDS, FIELD_MAP, PRESETS, QUICK, CATEGORIES } from './catalog.js';
import { normalizeConditions, screenStocks, coverage, conditionLabel } from './model.js';
import { escape as e, number } from '../research-ui.js';
const KEY='ox.tw.screener.v1';
let memory=null;
function read(){try{return JSON.parse(localStorage.getItem(KEY))||{};}catch{return {};}}
function write(value){try{localStorage.setItem(KEY,JSON.stringify(value));return true;}catch{return false;}}
export function mountScreener(host,{onOpenRadar=()=>{}}={}){
 const life=new AbortController(),root=document.createElement('section');root.className='tws';host.append(root);
 const stored=memory||read();let conditions=normalizeConditions(stored.conditions),scope=stored.scope||{},saved=Array.isArray(stored.saved)?stored.saved.filter(s=>s&&typeof s.id==='string'&&typeof s.name==='string').slice(-50):[],category='all',activePreset='',data=null,counts={},result=null,sort='turnover',query='',visible=50,loading=true;
 const mq=matchMedia('(max-width:760px)');
 root.innerHTML=`<link rel="stylesheet" href="${new URL('./style.css?v=20261005-weeklist4',import.meta.url)}"><div class="tws-title"><div><h2>台股篩選器 <span>50+ 條件</span></h2><p>自訂條件，建立你的觀察清單</p></div><button data-show-results>篩選結果 <b data-total>—</b></button></div><div class="tws-mobile-bar"><button class="tws-open" data-open-filters>☷ 條件 <b data-count>0</b></button><select data-quick-strategy disabled aria-label="快捷篩選策略"><option value="">選策略</option><option value="__browse">瀏覽策略庫</option><option value="__all">全部股票</option><optgroup label="快速篩選">${QUICK.map(p=>`<option value="${p.id}">${e(p.name)}</option>`).join('')}</optgroup><optgroup label="大師策略">${PRESETS.map(p=>`<option value="${p.id}">${e(p.name)}</option>`).join('')}</optgroup></select><button class="tws-primary" data-run disabled>篩選</button></div><div class="tws-chips" data-chips></div><div class="tws-layout"><aside class="tws-sidebar"></aside><main class="tws-main"><section class="tws-quick"><h3>快速篩選</h3><div>${QUICK.map(p=>`<button data-preset="${p.id}">${e(p.name)} <span>↗</span></button>`).join('')}</div></section><div class="tws-main-tabs"><button data-view="templates" aria-pressed="true">27 大師策略</button><button data-view="results" aria-pressed="false">篩選結果 <b data-total>—</b></button></div><div data-templates><p class="tws-muted">一鍵帶入條件，再依需求微調</p><nav class="tws-categories" aria-label="策略派別">${[['all','全部',27],...CATEGORIES].map(([id,name,count])=>`<button data-category="${id}" aria-pressed="${id==='all'}">${name}<small>${count}</small></button>`).join('')}</nav><div data-strategies></div></div><div data-results hidden></div><details class="tws-help"><summary>股票條件篩選可以怎麼用？</summary><p><b>估值與配息</b>：用殖利率、本益比與配息條件建立清單。</p><p><b>成長與獲利</b>：對照營收年增率與財報獲利能力。</p><p><b>籌碼與技術</b>：以法人、均線、量能整理觀察標的。</p><p>大師模板為 OX 依公開投資理念整理的量化參考，非本人完整策略或背書。配置派只能篩選候選股票，不代表完成資產配置。缺漏資料不當作零，也不會自動省略條件。</p><p>毛利率、營益率與淨利率依財報年初累計；季 EPS 只在可取得單季資料時納入。52週與240日條件須有足夠歷史。數據為盤後快照，非即時報價；條件由使用者設定，本工具不提供買賣建議。</p><div data-sources></div></details><div class="tws-status" role="status" data-status>正在載入官方盤後資料…</div></main></div><div class="tws-mobile-actions"><button class="tws-primary" data-run>篩選 <span data-count>0</span></button><button data-reset>↺ 重設</button></div>`;
 guardStyledContent(host,root,[root.querySelector('link[rel=stylesheet]')],life.signal,'.tws',360);
 const q=s=>root.querySelector(s),qa=s=>root.querySelectorAll(s);
 const panel=document.createElement('div');panel.className='tws-filter-panel';
 panel.innerHTML=`<div class="tws-chips" data-sheet-chips></div><div class="tws-saved"><h3>我的篩選組合</h3><div><select aria-label="我的篩選組合" data-saved><option value="">尚未儲存組合</option></select><button data-delete-saved aria-label="刪除選取組合">刪除</button></div><button data-save>＋ 儲存目前條件</button></div><div class="tws-filter-title"><h3>設定條件 <small>${FIELDS.length}</small></h3><span>已選 <b data-count>0</b></span></div><label class="tws-field-search">找條件<input type="search" data-field-search placeholder="例如：殖利率、營收、均線" aria-label="搜尋篩選條件"></label><p data-field-empty hidden>沒有符合的條件，請換個關鍵字。</p><div class="tws-fields">${GROUPS.map((g,i)=>`<details ${i<2?'open':''}><summary>${g.name}<span data-group-count="${g.id}"></span></summary><div>${g.fields.map(f=>f.type==='boolean'?`<label class="tws-toggle"><input type="checkbox" data-field="${f.id}" aria-label="${e(f.label)}"><span>${e(f.label)}</span><small data-coverage="${f.id}"></small></label>`:f.type==='rating'?`<fieldset class="tws-rating"><legend>Rating 評級</legend>${[['A','最高'],['B','較高'],['C','中等'],['D','較低'],['E','最低']].map(([v,l])=>`<label><input type="checkbox" data-rating="${v}">${l}</label>`).join('')}<small data-coverage="rating"></small></fieldset>`:`<label class="tws-field"><span>${e(f.label)}<small data-coverage="${f.id}"></small></span><span class="tws-number"><span>${f.op==='gte'?'≥':'≤'}</span><input type="number" inputmode="decimal" step="any" ${f.min!=null?`min="${f.min}"`:''} ${f.max!=null?`max="${f.max}"`:''} data-field="${f.id}" aria-label="${e(f.label)}"><small>${f.unit}</small></span></label>`).join('')}</div></details>`).join('')}</div><div class="tws-scope"><label>市場<select data-scope="market"><option value="">全部</option><option value="TWSE">上市</option><option value="TPEX">上櫃</option></select></label><label>產業<select data-scope="industry"><option value="">全部</option></select></label></div><div class="tws-filter-actions"><button class="tws-primary" data-run>篩選</button><button data-reset>↺ 重設</button></div>`;
 q('.tws-sidebar').append(panel);
 const dialog=document.createElement('dialog');dialog.className='tws-dialog tws';dialog.setAttribute('aria-label','設定篩選條件');dialog.innerHTML='<div class="tws-sheet-head"><h3>設定篩選條件</h3><button data-close aria-label="關閉條件面板">✕</button></div><div data-sheet-body></div>';document.body.append(dialog);
 const saveDialog=document.createElement('dialog');saveDialog.className='tws-dialog tws tws-save-dialog';saveDialog.setAttribute('aria-label','儲存篩選組合');saveDialog.innerHTML='<form><h3>儲存篩選組合</h3><label>組合名稱<input name="name" required maxlength="40" autocomplete="off" placeholder="例如：我的高股息觀察"></label><p class="tws-muted">儲存在此瀏覽器，可隨時重新套用。</p><div><button type="button" data-cancel>取消</button><button class="tws-primary" type="submit">儲存</button></div></form>';document.body.append(saveDialog);
 const all=s=>[...root.querySelectorAll(s),...dialog.querySelectorAll(s)];
 function status(text){q('[data-status]').textContent=text;}
 function persist(){const value={conditions,scope,saved};memory=value;if(!write(value))status('瀏覽器無法儲存設定；目前條件仍可使用。');}
 function sync(){for(const el of all('[data-field]')){const v=conditions[el.dataset.field];if(el.type==='checkbox')el.checked=v===true;else el.value=v??'';}all('[data-rating]').forEach(el=>el.checked=(conditions.rating||[]).includes(el.dataset.rating));all('[data-scope]').forEach(el=>el.value=scope[el.dataset.scope]||'');chips();}
 function dirty(){result=null;all('[data-total]').forEach(x=>x.textContent='—');q('[data-results]').innerHTML='<p class="tws-notice">條件已變更，按「篩選」更新結果。</p>';}
 function chips(){all('[data-count]').forEach(el=>el.textContent=Object.keys(conditions).length);for(const g of GROUPS){const el=panel.querySelector(`[data-group-count="${g.id}"]`);const n=g.fields.filter(f=>conditions[f.id]!=null).length;el.textContent=n||'';}
 q('[data-chips]').innerHTML=Object.entries(conditions).map(([k,v])=>`<button data-remove="${k}" title="移除條件">${e(conditionLabel(k,v))}<span>×</span></button>`).join('');panel.querySelector('[data-sheet-chips]').innerHTML=q('[data-chips]').innerHTML;}
 function savedList(){const el=panel.querySelector('[data-saved]'),selected=el.value;el.innerHTML='<option value="">'+(saved.length?'選擇已儲存組合':'尚未儲存任何篩選組合')+'</option>'+saved.map(x=>`<option value="${e(x.id)}">${e(x.name)}</option>`).join('');el.value=selected;}
 function templates(){q('[data-strategies]').innerHTML=CATEGORIES.filter(([id])=>category==='all'||id===category).map(([id,name,count])=>`<section class="tws-strategy-group"><h3>${name}<small>${count}</small></h3><div class="tws-strategy-grid">${PRESETS.filter(x=>x.category===id).map(p=>{const missing=Object.keys(p.conditions).filter(id=>data&&!counts[id]);return `<button class="tws-strategy ${activePreset===p.id?'active':''}" data-preset="${p.id}" aria-pressed="${activePreset===p.id}"><strong>${e(p.name)}</strong><span>${e(p.spirit)}</span><small>${Object.keys(p.conditions).length} 條件${missing.length?' · '+missing.length+' 項待資料':''}</small><i>↗</i></button>`;}).join('')}</div></section>`).join('');}
 function view(which){root.dataset.view=which;qa('[data-view]').forEach(x=>x.setAttribute('aria-pressed',String(x.dataset.view===which)));q('[data-templates]').hidden=which!=='templates';q('[data-results]').hidden=which!=='results';}
 function renderRows(){if(!result)return;let rows=result.rows.filter(s=>!query||`${s.symbol} ${s.name}`.toLowerCase().includes(query.toLowerCase()));rows=[...rows].sort((a,b)=>sort==='symbol'?a.symbol.localeCompare(b.symbol):(b[sort]??-Infinity)-(a[sort]??-Infinity));const shown=rows.slice(0,visible);
 const unsupported=Object.keys(conditions).filter(id=>!counts[id]);
 q('[data-results]').innerHTML=`<div class="tws-results-head"><div><h3>${rows.length.toLocaleString()} 檔符合條件</h3><p>${e(data.date)} 盤後 · 範圍 ${result.eligible.toLocaleString()} 檔 · ${result.missing.toLocaleString()} 檔資料不完整已排除</p></div></div>${unsupported.length?`<div class="tws-notice" role="status">以下條件尚無可用資料：${unsupported.map(id=>e(FIELD_MAP[id].label)).join('、')}。條件已保留，取得資料前不會回傳誤導結果。</div>`:''}<div class="tws-results-tools"><input type="search" data-search aria-label="搜尋篩選結果" placeholder="搜尋代號／名稱" value="${e(query)}"><select data-sort aria-label="結果排序">${[['turnover','成交金額 ↓'],['yield','殖利率 ↓'],['return5','5日漲幅 ↓'],['symbol','代號 ↑']].map(([id,name])=>`<option value="${id}" ${sort===id?'selected':''}>${name}</option>`).join('')}</select></div><div class="tws-results-scroll"><table><thead><tr><th>股票</th><th>收盤</th><th>漲跌幅</th><th>殖利率</th><th>P/E</th><th>月營收 YoY</th><th>量比</th><th></th></tr></thead><tbody>${shown.map(s=>`<tr><td><button data-stock="${e(s.symbol)}"><b>${e(s.name)}</b><small>${e(s.symbol)} · ${s.market==='TWSE'?'上市':'上櫃'}</small></button></td><td>${number(s.price)}</td><td class="${s.changePct>0?'tws-up':s.changePct<0?'tws-down':''}">${number(s.changePct)}%</td><td>${number(s.yield)}${s.yield!=null?'%':''}</td><td>${number(s.pe)}</td><td>${number(s.revenueYoY)}${s.revenueYoY!=null?'%':''}</td><td>${number(s.volumeRatio)}</td><td><button data-detail="${e(s.symbol)}" aria-label="${e(s.name)}資料明細">明細</button></td></tr>`).join('')}</tbody></table></div>${!rows.length?'<div class="tws-empty">沒有符合全部條件的股票，可調整條件後再次篩選。</div>':''}${rows.length>visible?'<button class="tws-more" data-more>載入更多</button>':''}`;
 labelResults();
 }
 function labelResults(){const table=q('[data-results] table');if(!table)return;const labels=[...table.querySelectorAll('th')].map(n=>n.textContent);for(const row of table.querySelectorAll('tbody tr'))[...row.cells].forEach((cell,i)=>{if(i&&i<7)cell.dataset.label=labels[i];});}
 function run({scroll=true}={}){if(!data){status('資料尚未載入完成，請稍候。');return;}if(!panel.querySelector('input:invalid')){result=screenStocks(data.stocks,conditions,scope);visible=50;all('[data-total]').forEach(x=>x.textContent=result.rows.length);renderRows();view('results');closeFilters();persist();status(`篩選完成：${result.rows.length} 檔符合，資料日期 ${data.date}`);if(scroll&&!mq.matches)q('.tws-main-tabs').scrollIntoView({block:'start',behavior:'smooth'});}else{openFilters();panel.querySelector('input:invalid').reportValidity();}}
 function openFilters(){if(!mq.matches)return;dialog.querySelector('[data-sheet-body]').append(panel);dialog.showModal();}
 function closeFilters(){if(dialog.open)dialog.close();q('.tws-sidebar').append(panel);}
 function apply(id){const preset=[...PRESETS,...QUICK].find(p=>p.id===id);if(!preset)return;conditions={...preset.conditions};activePreset=id;dirty();sync();templates();persist();const missing=Object.keys(conditions).filter(k=>data&&!counts[k]);status(`已套用 ${preset.name}，${Object.keys(conditions).length} 個條件${missing.length?'；其中 '+missing.length+' 項尚待資料':''}。按「篩選」執行。`);}
 const detail=document.createElement('dialog');detail.className='tws-dialog tws tws-detail';detail.setAttribute('aria-label','股票篩選資料');document.body.append(detail);
 function showDetail(symbol){const s=data.stocks.find(s=>s.symbol===symbol);if(!s)return;detail.innerHTML=`<div class="tws-sheet-head"><h3>${e(s.name)} ${e(s.symbol)}</h3><button data-detail-close aria-label="關閉資料明細">✕</button></div><p>行情 ${e(s.dataDate||data.date)} · 估值 ${e(s.valuationDate||'未提供')} · 營收 ${e(s.revenuePeriod||'未提供')} · 財報 ${e(s.financialPeriod||'未提供')}</p><dl>${FIELDS.filter((f,i,a)=>a.findIndex(x=>x.metric===f.metric)===i).map(f=>`<div><dt>${e(f.label.replace(/下限|上限/g,''))}</dt><dd>${s[f.metric]==null?'—':f.type==='boolean'?(s[f.metric]?'是':'否'):number(s[f.metric])+e(f.unit)}</dd></div>`).join('')}</dl><p class="tws-muted">— 表示缺少驗證資料；不同來源發布期別可能不同。</p>`;detail.showModal();}
 function click(event){const b=event.target.closest('button');if(!b)return;if(b.hasAttribute('data-open-filters'))openFilters();if(b.hasAttribute('data-close'))closeFilters();if(b.hasAttribute('data-run'))run();if(b.hasAttribute('data-reset')){conditions={};scope={};activePreset='';result=null;all('[data-total]').forEach(x=>x.textContent='—');q('[data-results]').innerHTML='';sync();templates();view('templates');persist();status('已清空所有條件與範圍。');q('[data-quick-strategy]').value='';if(mq.matches)run({scroll:false});}if(b.dataset.preset)apply(b.dataset.preset);if(b.dataset.category){category=b.dataset.category;qa('[data-category]').forEach(el=>el.setAttribute('aria-pressed',String(el===b)));templates();}if(b.dataset.view)view(b.dataset.view);if(b.hasAttribute('data-show-results'))result?view('results'):run();if(b.dataset.remove){delete conditions[b.dataset.remove];dirty();sync();persist();}if(b.hasAttribute('data-save')){closeFilters();saveDialog.showModal();}if(b.hasAttribute('data-delete-saved')){const id=panel.querySelector('[data-saved]').value;saved=saved.filter(x=>x.id!==id);savedList();persist();}if(b.dataset.stock)onOpenRadar(b.dataset.stock);if(b.dataset.detail)showDetail(b.dataset.detail);if(b.hasAttribute('data-more')){visible+=50;renderRows();}}
 function input(event){const el=event.target;if(el.hasAttribute('data-field-search')){const term=el.value.trim().toLowerCase();let total=0;for(const group of panel.querySelectorAll('.tws-fields details')){let count=0;for(const field of group.querySelectorAll('.tws-field,.tws-toggle,.tws-rating')){const show=!term||field.textContent.toLowerCase().includes(term);field.hidden=!show;if(show)count++;}group.hidden=!count;if(term&&count)group.open=true;total+=count;}panel.querySelector('[data-field-empty]').hidden=total>0;return;}if(el.dataset.field){dirty();const id=el.dataset.field;if(el.type==='checkbox'){if(el.checked)conditions[id]=true;else delete conditions[id];}else if(el.value==='')delete conditions[id];else if(el.validity.valid)conditions[id]=Number(el.value);chips();persist();}if(el.dataset.rating){dirty();conditions.rating=all('[data-rating]:checked').map(x=>x.dataset.rating);if(!conditions.rating.length)delete conditions.rating;chips();persist();}if(el.dataset.scope){dirty();scope[el.dataset.scope]=el.value;persist();}}
 for(const target of [root,dialog]){target.addEventListener('click',click,{signal:life.signal});target.addEventListener('input',input,{signal:life.signal});}
 dialog.addEventListener('close',()=>q('.tws-sidebar').append(panel),{signal:life.signal});mq.addEventListener('change',()=>{if(!mq.matches)closeFilters();},{signal:life.signal});
 root.addEventListener('input',ev=>{if(ev.target.hasAttribute('data-search')){query=ev.target.value;const pos=ev.target.selectionStart;renderRows();const el=q('[data-search]');el.focus();el.setSelectionRange(pos,pos);}},{signal:life.signal});
 root.addEventListener('change',ev=>{if(ev.target.hasAttribute('data-quick-strategy')){const id=ev.target.value;if(id==='__browse'){view('templates');return;}if(id==='__all'){conditions={};scope={};activePreset='';sync();persist();}else if(id)apply(id);if(id)run({scroll:false});}if(ev.target.hasAttribute('data-sort')){sort=ev.target.value;renderRows();}},{signal:life.signal});
 panel.addEventListener('change',ev=>{if(ev.target.hasAttribute('data-saved')){const item=saved.find(x=>x.id===ev.target.value);if(item){conditions=normalizeConditions(item.conditions);scope=item.scope||{};activePreset='';dirty();sync();persist();status('已載入 '+item.name);}}},{signal:life.signal});
 saveDialog.querySelector('[data-cancel]').onclick=()=>saveDialog.close();saveDialog.querySelector('form').onsubmit=ev=>{ev.preventDefault();const name=saveDialog.querySelector('input').value.trim();if(!name)return;saved=[...saved,{id:crypto.randomUUID(),name,conditions:{...conditions},scope:{...scope}}].slice(-50);savedList();persist();saveDialog.close();status('已儲存「'+name+'」。');};
 detail.addEventListener('click',ev=>{if(ev.target.closest('[data-detail-close]'))detail.close();},{signal:life.signal});savedList();sync();templates();if(mq.matches){view('results');q('[data-results]').innerHTML='<p class="tws-notice" role="status">正在載入篩選結果…</p>';}
 fetch(new URL('../../../../data/tw-screener.json.gz',import.meta.url),{signal:AbortSignal.any([life.signal,AbortSignal.timeout(12000)]),cache:'no-cache'}).then(r=>{if(!r.ok)throw Error('snapshot');return r.headers.get('content-encoding')?.includes('gzip')?r.json():new Response(r.body.pipeThrough(new DecompressionStream('gzip'))).json();}).then(snapshot=>{if(!snapshot.date||!Array.isArray(snapshot.stocks)||!snapshot.stocks.length)throw Error('empty');data=snapshot;loading=false;q('[data-quick-strategy]').disabled=false;qa('[data-run]').forEach(b=>b.disabled=false);counts=coverage(data.stocks);panel.querySelector('[data-scope="industry"]').innerHTML='<option value="">全部</option>'+[...new Set(data.stocks.map(s=>s.industry))].filter(Boolean).sort().map(s=>`<option value="${e(s)}">${e(s)}</option>`).join('');for(const f of FIELDS){const el=panel.querySelector(`[data-coverage="${f.id}"]`);el.textContent=counts[f.id]?'':f.note||'尚無資料';el.title=`${counts[f.id]} 檔有可用資料`;}sync();templates();status(`${data.date} 盤後 · ${data.stocks.length.toLocaleString()} 檔 · 缺少資料的條件不會自動省略`);q('[data-sources]').innerHTML='<p>資料來源與發布狀態</p>'+Object.values(data.sources||{}).map(s=>`<p><a href="${e(s.url)}" target="_blank" rel="noopener">${e(s.name)}</a> · ${s.ok?'已取得':'未取得'}${s.retained?'（保留上次資料）':''}</p>`).join('');if(mq.matches)run({scroll:false});}).catch(error=>{if(error.name!=='AbortError'){loading=false;status('篩選資料暫時無法載入，請重新進入此工具。');if(mq.matches)q('[data-results]').innerHTML='<p class="tws-notice" role="status">篩選資料暫時無法載入，請重新進入此工具。</p>';}});
 return {destroy(){life.abort();dialog.remove();saveDialog.remove();detail.remove();root.remove();}};
}
